aide/urls.py
# coding: utf-8
from django.urls import path, re_path

from aide import views


app_name = 'aide'
urlpatterns = [
    # Aide : sommaire
    path('', views.view_help_page, {"path": "sommaire"}, name="help-sommaire"),

    # Aide : liste
    path('liste', views.view_help_list, name="help-list"),

    # Aide contextuelle
    re_path('context/(?P<name>.+)', views.view_context_help, name="context"),

    # formulaire de demande
    path('contact', views.demande, name="contact"),

    # Aide : page
    re_path('(?P<path>[a-zA-Z0-9-/_]+)/(?P<pk>\d+)', views.view_help_page, name="help-accordion-page-direct"),
    re_path('(?P<path>.+)', views.view_help_page, name="help-page"),
]

api/urls.py
from django.urls import include, path
from api import views as api_views
from rest_framework import routers


app_name = 'api'
router = routers.DefaultRouter()
# router.register(r'manifestations', api_views.ManifestationAllViewSet)
router.register(r'ManifestationAutorisation', api_views.ManifestationAutorisationViewSet, base_name='ManifestationAutorisation')
router.register(r'ManifestationDeclaration', api_views.ManifestationDeclarationViewSet, base_name='ManifestationDeclaration')
router.register(r'Organisateur', api_views.OrganisateurViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

events/urls.py
# coding: utf-8
from django.urls import path, re_path

from events.views.autorisationnm import AutorisationNMFilesUpdate
from events.views.declarationnm import DeclarationNMFilesUpdate
from events.views.motorizedconcentration import MotorizedConcentrationFilesUpdate
from events.views.motorizedmanifestation import MotorizedEventFilesUpdate
from events.views.motorizedrace import MotorizedRaceFilesUpdate
from .views import ManifestationStartChoose
from .views import Dashboard
from .views import UnsupportedManifestationCreate
from .views import ManifestationInstructeurUpdate
from .views import AutorisationNMCreate
from .views import AutorisationNMDetail
from .views import AutorisationNMUpdate
from .views import CreateRoute
from .views import DeclarationNMChoose
from .views import DeclarationNMCreate
from .views import DeclarationNMDetail
from .views import DeclarationNMUpdate
from .views import DocumentComplementaireProvideView
from .views import DocumentComplementaireRequestView
from .views import MailToOrganisateursView
from .views import MailToTownHallsView
from .views import ManifestationChoose
from .views import ManifestationPublicDetail
from .views import MotorizedConcentrationCreate
from .views import MotorizedConcentrationDetail
from .views import MotorizedConcentrationUpdate
from .views import MotorizedEventChoose
from .views import MotorizedEventCreate
from .views import MotorizedEventDetail
from .views import MotorizedEventUpdate
from .views import MotorizedRaceCreate
from .views import MotorizedRaceDetail
from .views import MotorizedRaceUpdate
from .views import NonMotorizedEventChoose
from .views import PublicRoadMotorizedEventChoose
from organisateurs.views import StructureCreate


app_name = 'events'
urlpatterns = [

    # Tableau de bord principal
    path('dashboard/', Dashboard.as_view(), name="dashboard"),

    path('mail_to_promoters/', MailToOrganisateursView.as_view(), name='mail_to_promoters'),
    path('mail_to_townhalls/', MailToTownHallsView.as_view(), name='mail_to_townhalls'),
    path('structure/add', StructureCreate.as_view(), name='structure_add'),

    path('events/choose_start/', ManifestationStartChoose.as_view(), name='manifestation_start_choose'),
    path('events/create_route/', CreateRoute.as_view(), name='create_route'),
    path('events/choose/', ManifestationChoose.as_view(), name='manifestation_choose'),
    path('motorizedevents/choose', MotorizedEventChoose.as_view(), name="motorizedevent_choose"),
    path('nonmotorizedevents/choose', NonMotorizedEventChoose.as_view(), name="nonmotorizedevent_choose"),
    path('DeclarationNM/choose', DeclarationNMChoose.as_view(), name="declarationnm_choose"),
    path('publicroadmotorizedevents/choose', PublicRoadMotorizedEventChoose.as_view(), name="publicroadmotorizedevent_choose"),

    # Manifestation sans type (non supporté)
    path('unsupported/add/', UnsupportedManifestationCreate.as_view(), name="unsupported_manifestation_add"),

    # Modifications instructeur
    re_path('event/(?P<pk>\d+)/instruction/', ManifestationInstructeurUpdate.as_view(), name="manifestation_instructeur"),
    re_path('event/(?P<manifestation_pk>\d+)/additional_data/add', DocumentComplementaireRequestView.as_view(), name="additional_data_add"),
    re_path('event/(?P<pk>\d+)/', ManifestationPublicDetail.as_view(), name="manifestation_detail"),

    # DeclarationNM urls
    path('DeclarationNM/add/', DeclarationNMCreate.as_view(), name="declarationnm_add"),
    re_path('DeclarationNM/(?P<pk>\d+)/edit/', DeclarationNMUpdate.as_view(), name="declarationnm_update"),
    re_path('DeclarationNM/(?P<pk>\d+)/edit_files/', DeclarationNMFilesUpdate.as_view(), name="declarationnm_files_update"),
    re_path('DeclarationNM/(?P<pk>\d+)/', DeclarationNMDetail.as_view(), name="declarationnm_detail"),

    # AutorisationNM urls
    path('AutorisationNM/add/', AutorisationNMCreate.as_view(), name="autorisationnm_add"),
    re_path('AutorisationNM/(?P<pk>\d+)/edit/', AutorisationNMUpdate.as_view(), name="autorisationnm_update"),
    re_path('AutorisationNM/(?P<pk>\d+)/edit_files/', AutorisationNMFilesUpdate.as_view(), name="autorisationnm_files_update"),
    re_path('AutorisationNM/(?P<pk>\d+)/', AutorisationNMDetail.as_view(), name="autorisationnm_detail"),

    # MotorizedConcentration urls
    path('motorizedconcentrations/add/', MotorizedConcentrationCreate.as_view(), name="motorizedconcentration_add"),
    re_path('motorizedconcentrations/(?P<pk>\d+)/edit/', MotorizedConcentrationUpdate.as_view(), name="motorizedconcentration_update"),
    re_path('motorizedconcentrations/(?P<pk>\d+)/edit_files/', MotorizedConcentrationFilesUpdate.as_view(), name="motorizedconcentration_files_update"),
    re_path('motorizedconcentrations/(?P<pk>\d+)/', MotorizedConcentrationDetail.as_view(), name="motorizedconcentration_detail"),

    # MotorizedEvent urls
    path('motorizedevents/add/', MotorizedEventCreate.as_view(), name="motorizedevent_add"),
    re_path('motorizedevents/(?P<pk>\d+)/edit/', MotorizedEventUpdate.as_view(), name="motorizedevent_update"),
    re_path('motorizedevents/(?P<pk>\d+)/edit_files/', MotorizedEventFilesUpdate.as_view(), name="motorizedevent_files_update"),
    re_path('motorizedevents/(?P<pk>\d+)/', MotorizedEventDetail.as_view(), name="motorizedevent_detail"),

    # MotorizedRace urls
    path('motorizedraces/add/', MotorizedRaceCreate.as_view(), name="motorizedrace_add"),
    re_path('motorizedraces/(?P<pk>\d+)/edit/', MotorizedRaceUpdate.as_view(), name="motorizedrace_update"),
    re_path('motorizedraces/(?P<pk>\d+)/edit_files/', MotorizedRaceFilesUpdate.as_view(), name="motorizedrace_files_update"),
    re_path('additional_data/(?P<pk>\d+)/', DocumentComplementaireProvideView.as_view(), name="additional_data_provide"),
    re_path('motorizedraces/(?P<pk>\d+)/', MotorizedRaceDetail.as_view(), name="motorizedrace_detail"),

]

portail/urls.py
# coding: utf-8
from django.urls import path, re_path

from .views.calendar import Calendar
from .views.calendar import FilteredCalendar
from .views.index import HomePage
from .views.stat import Stat


app_name = 'portail'
urlpatterns = [

    # Accueil
    path('', HomePage.as_view(), name='home_page'),

    # Calendrier
    re_path('calendar/(?P<activite>\d+)/', FilteredCalendar.as_view(), name="filtered_calendar"),
    path('calendar/', Calendar.as_view(), name="calendar"),
    path('stat/', Stat.as_view(), name="stat"),

]

portail/views/calendar.py
# coding: utf-8
from django.db.models import Count
from django.utils import timezone
from django.views.generic import ListView

from core.models.instance import Instance
from events.forms import *
from events.models import *


class Calendar(ListView):
    """ Calendrier des manifestations """

    # Configuration
    model = Manifestation
    template_name = 'portail/calendar.html'

    # Overrdes
    def get_queryset(self):
        now = timezone.now()
        instance = Instance.objects.get_for_request(self.request)
        departement = instance.get_departement()
        to_display = Manifestation.objects.filter(
            ~Q(autorisationnm__manifestationautorisation__id=None) |
            ~Q(declarationnm__manifestationdeclaration__id=None) |
            ~Q(motorizedevent__manifestationautorisation__id=None) |
            ~Q(motorizedrace__manifestationautorisation__id=None) |
            ~Q(motorizedconcentration__manifestationautorisation__id=None) |
            ~Q(motorizedconcentration__manifestationdeclaration__id=None),
            begin_date__gt=now,
        ).order_by('begin_date')
        # Afficher les manifs du département, ou aucune sur le domaine master
        if departement is not None:
            to_display = to_display.filter(departure_city__arrondissement__departement=departement)
        else:
            to_display = to_display.none()
        return to_display

    def get_context_data(self, **kwargs):
        now = timezone.now()
        context = super(Calendar, self).get_context_data(**kwargs)
        # manif = Count('manifestations', filter=Q(manifestations__instance=Instance.objects.get_for_request(self.request)))
        liste1 = Activite.objects.filter(
            Q(manifestations__begin_date__gt=now) &
            Q(manifestations__hidden=False) &
            Q(manifestations__private=False) &
            Q(manifestations__departure_city__arrondissement__departement__name__icontains='42') &
            Q(manifestations__manifestationautorisation__id__isnull=False))
        liste2 = Activite.objects.filter(
            Q(manifestations__begin_date__gt=now) &
            Q(manifestations__hidden=False) &
            Q(manifestations__private=False) &
            Q(manifestations__departure_city__arrondissement__departement__name__icontains='42') &
            Q(manifestations__manifestationdeclaration__id__isnull=False))
        liste = liste1.union(liste2)
        context['activities'] = liste.order_by('name')
        return context


class FilteredCalendar(Calendar):
    """ Calendrier des manifestations par activité """

    # Overrides
    def get_queryset(self):
        return super(FilteredCalendar, self).get_queryset().filter(activite=self.kwargs['activite'])

    def get_context_data(self, **kwargs):
        context = super(FilteredCalendar, self).get_context_data(**kwargs)
        context['current_activite'] = int(self.kwargs['activite'])
        return context

portail/views/index.py
# coding: utf-8
from django.views.generic.base import TemplateView
from django.shortcuts import render

from core.models.instance import Instance


class HomePage(TemplateView):
    """ Page d'accueil """

    # Configuration
    template_name = 'portail/index.html'

    # Méthodes
    def get_context_data(self, **kwargs):
        """ Définir le contexte d'affichage de la page """
        context = super(HomePage, self).get_context_data(**kwargs)
        instance = Instance.objects.get_for_request(self.request)
        context['INSTANCES'] = Instance.objects.configured()
        # Doamine sans instance : ne pas afficher le calendrier
        context['HIDE_CALENDAR'] = instance.is_master()
        return context

def forbidden_view(request, exception):
    return render(request,'403.html', {'message': exception}, status=403)

portail/views/stat.py
# coding: utf-8
from django.views.generic.base import TemplateView
from django.contrib.sessions.models import Session
from django.db.models import Count
from django.utils import timezone
from core.models import User
from events.models import Manifestation
from agreements.models import Avis
from sub_agreements.models import PreAvis
from organisateurs.models import Organisateur

from collections import OrderedDict

class Stat(TemplateView):
    """ Page de statistique """

    # Configuration
    template_name = 'stat.html'

    def get_current_users(self):
        active_sessions = Session.objects.filter(expire_date__gte=timezone.now())
        user_id_list = []
        for session in active_sessions:
            data = session.get_decoded()
            user_id_list.append(data.get('_auth_user_id', None))
        return User.objects.filter(id__in=user_id_list)

    def count_by_year(self, **kwargs):
        data = None
        if "liste" in kwargs and "critere" in kwargs:
            liste = kwargs.get('liste')
            critere = kwargs.get('critere')
            data = {}
            for y in range(2014, timezone.now().year + 2):
                filter = critere + "__contains"
                data[y] = liste.filter(**{filter: y}).count()
        return OrderedDict(sorted(data.items(), key=lambda t: t[0]))

    def get_context_data(self, **kwargs):
        stat = {}
        stat['annees'] = range(2014, timezone.now().year + 2)

        stat['connected_user'] = self.get_current_users().count()

        stat['nb_utilisateur'] = User.objects.count()
        stat['nb_utilisateur_par_annee'] = self.count_by_year(liste = User.objects, critere = "date_joined")

        stat['nb_organisateur'] = Organisateur.objects.count()
        stat['nb_organisateur_par_annee'] = self.count_by_year(liste = Organisateur.objects, critere = "user__date_joined")

        stat['nb_manif_prevue'] = Manifestation.objects.count()
        stat['nb_manif_prevue_par_annee'] = self.count_by_year(liste = Manifestation.objects, critere = "begin_date")

        stat['nb_manif_cree'] = Manifestation.objects.count()
        stat['nb_manif_cree_par_annee'] = self.count_by_year(liste = Manifestation.objects, critere = "creation_date")

        # Code commenté car execution très lente
        # stat['nb_manif_validee'] = [m.processing() for m in Manifestation.objects.all()].count(True)
        # data = {}
        # for y in range(2014, timezone.now().year + 2):
        #     data[y] = [m.processing() for m in Manifestation.objects.filter(begin_date__contains=y).all()].count(True)
        # stat['nb_manif_validee_par_annee'] = data

        stat['nb_manif_une_commune'] = Manifestation.objects.annotate(nbr_cities=Count('crossed_cities')).filter(nbr_cities=1).count()
        stat['nb_manif_une_commune_par_annee'] = self.count_by_year(liste = Manifestation.objects.annotate(nbr_cities=Count('crossed_cities')).filter(nbr_cities=1), critere = "begin_date")

        stat['count_avis'] = Avis.objects.all().count()
        stat['count_avis_par_annee'] = self.count_by_year(liste = Avis.objects, critere = "request_date")

        stat['count_preavis'] = PreAvis.objects.count()
        stat['count_preavis_par_annee'] = self.count_by_year(liste = PreAvis.objects, critere = "request_date")

        context = super().get_context_data(**kwargs)
        context['stat'] = stat
        return context

portail/templates/portail/calendar.html
{% extends "base.html" %}


{% load i18n %}

{% block head_title %}
    Calendrier
{% endblock %}

{% block page_title %}
    <h1>Manifestations sportives à venir dans le département {{ INSTANCE.get_departement }}</h1>
{% endblock %}

{% block content %}
    <div class="container">
        {% for activite in activities %}
            <a href="{% url 'portail:filtered_calendar' activite=activite.pk %}" class="btn {% if current_activite == activite.id %}btn-primary{% else %}btn-outline-secondary{% endif %} btn-sm">
                {{ activite|title }}
            </a>
        {% endfor %}
        <a href="{% url 'portail:calendar' %}" class="btn btn-outline-secondary btn-sm">Toutes les activités</a>
    </div>
    <br>
        <div class="col-sm-6">
            <div id="accordion" role="tablist" aria-multiselectable="true">
                {% regroup object_list by begin_date|date:"F Y" as months %}
                {% for month in months %}
                    <div class="card ">
                        <div class="card-header" role="tab" id="heading{{ forloop.counter }}">
                            <h4 class="card-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#collapse{{ forloop.counter }}" aria-expanded="true" aria-controls="collapse{{ forloop.counter }}">
                                    {{ month.grouper }}
                                </a>
                            </h4>
                        </div>
                        <div id="collapse{{ forloop.counter }}" class="card-collapse collapse{% if forloop.first %} show {% endif %}" role="tabpanel" aria-labelledby="heading{{ forloop.counter }}" data-parent="#accordion">
                            <ul class="list-group">
                                {% for manifestation in month.list %}
                                    {% if manifestation.is_visible_in_calendar %}
                                        <a href="{% url 'events:manifestation_detail' manifestation.id %}" class="list-group-item list-group-item-action">
                                            <small>{{ manifestation.begin_date|date:"l j" }}</small>
                                            <br/>{{ manifestation }}
                                            <br/><small>Départ à {{ manifestation.departure_city }}</small>
                                            {% if manifestation.manifestationautorisation.state != 'published' %}
                                                <br><strong class="text-info">En cours d'instruction</strong>
                                            {% endif %}
                                        </a>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        {% comment %}
            <div class="col-sm-6">
                {% include 'events/map.html' %}
            </div>
        {% endcomment %}
{% endblock %}

portail/templates/portail/index.html
{% extends "base.html" %}

{% load staticfiles %}
{% load i18n %}


{% block head_title %} Manifestations Sportives | Plateforme {{ INSTANCE.get_departement_friendly_name }}
{% endblock %}

{% block body %}
    {% block content %}
        {# Le commentaire HTML ci-dessous doit être conservé !! #}
        <!-- Sous-domaine {{ INSTANCE.name }} -->

        <!-- bof #carrousel -->
        <div id="carrousel" class="carousel slide hidden-xs hidden-sm" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carrousel" data-slide-to="0" class="active"></li>
                <li data-target="#carrousel" data-slide-to="1"></li>
                <li data-target="#carrousel" data-slide-to="2"></li>
                <li data-target="#carrousel" data-slide-to="3"></li>
                <li data-target="#carrousel" data-slide-to="4"></li>
                <li data-target="#carrousel" data-slide-to="5"></li>
                <li data-target="#carrousel" data-slide-to="6"></li>
                <li data-target="#carrousel" data-slide-to="7"></li>
                <li data-target="#carrousel" data-slide-to="8"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img alt="slide" src="{% static 'portail/img/carousel01.jpg' %}">
                    <div class="carousel-caption">
                        <span class="carousel-caption-text">Démarches en ligne de déclarations et autorisation d'évènements sportifs</span>
                        <span class="carousel-caption-link" role="button" href="/about/">En savoir plus</span>
                    </div>
                </div>
                <div class="carousel-item">
                    <img alt="slide" src="{% static 'portail/img/carousel02.jpg' %}">
                    <div class="carousel-caption">
                        <span class="carousel-caption-text">Démarches en ligne de déclarations et autorisation d'évènements sportifs</span>
                        <span class="carousel-caption-link" role="button" href="/about/">En savoir plus</span>
                    </div>
                </div>
                <div class="carousel-item">
                    <img alt="slide" src="{% static 'portail/img/carousel03.jpg' %}">
                    <div class="carousel-caption">
                        <span class="carousel-caption-text">Démarches en ligne de déclarations et autorisation d'évènements sportifs</span>
                        <span class="carousel-caption-link" role="button" href="/about/">En savoir plus</span>
                    </div>
                </div>
                <div class="carousel-item">
                    <img alt="slide" src="{% static 'portail/img/carousel04.jpg' %}">
                    <div class="carousel-caption">
                        <span class="carousel-caption-text">Démarches en ligne de déclarations et autorisation d'évènements sportifs</span>
                        <span class="carousel-caption-link" role="button" href="/about/">En savoir plus</span>
                    </div>
                </div>
                <div class="carousel-item">
                    <img alt="slide" src="{% static 'portail/img/carousel05.jpg' %}">
                    <div class="carousel-caption">
                        <span class="carousel-caption-text">Démarches en ligne de déclarations et autorisation d'évènements sportifs</span>
                        <span class="carousel-caption-link" role="button" href="/about/">En savoir plus</span>
                    </div>
                </div>
                <div class="carousel-item">
                    <img alt="slide" src="{% static 'portail/img/carousel06.jpg' %}">
                    <div class="carousel-caption">
                        <span class="carousel-caption-text">Démarches en ligne de déclarations et autorisation d'évènements sportifs</span>
                        <span class="carousel-caption-link" role="button" href="/about/">En savoir plus</span>
                    </div>
                </div>
                <div class="carousel-item">
                    <img alt="slide" src="{% static 'portail/img/carousel07.jpg' %}">
                    <div class="carousel-caption">
                        <span class="carousel-caption-text">Démarches en ligne de déclarations et autorisation d'évènements sportifs</span>
                        <span class="carousel-caption-link" role="button" href="/about/">En savoir plus</span>
                    </div>
                </div>
                <div class="carousel-item">
                    <img alt="slide" src="{% static 'portail/img/carousel08.jpg' %}">
                    <div class="carousel-caption">
                        <span class="carousel-caption-text">Démarches en ligne de déclarations et autorisation d'évènements sportifs</span>
                        <span class="carousel-caption-link" role="button" href="/about/">En savoir plus</span>
                    </div>
                </div>
            </div>
            <!-- Controls -->
            <a class="left carousel-control-prev" href="#carrousel" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            </a>
            <a class="right carousel-control-next" href="#carrousel" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
            </a>
        </div>
        <!-- eof #carrousel -->

        <!-- bof contenu -->
        <div class='container'>
        <div class="row">

            <!-- bof 1e colonne -->
            <div class="col-md-4 background-contrast">

                <div id="carte-fr" style="width: 100%; "></div>

                <script type="text/javascript">
                    var instances = {};
                    {% for instance in INSTANCES %}
                        // Todo : à réactiver après la mise en place d'un certificat avec tous les sous-domaines sachant qu'il y a une erreur avec request.META.SERVER_NAME
                        // instances["FR-{{ instance.get_departement.name }}"] = "{{ request.is_secure|yesno:"https,http" }}://{{ instance.get_departement.name }}.{{ request.META.SERVER_NAME }}:{{ request.META.SERVER_PORT }}";
                        instances["FR-{{ instance.get_departement.name }}"] = "http://{{ instance.get_departement.name }}.manifestationsportive.fr";
                    {% endfor %}
                </script>

            </div>
            <!-- eof 1e colonne -->

            <!-- bof 2e colonne -->
            <div class="col-md-8">

                <!-- bof ligne de titre -->
                <div class="row background-contrast">
                    <div class="col-md-6">

                        <div class="cadre-blanc">
                            <h1 class="text-center h1-home">
                                MANIFESTATIONS SPORTIVES<br/>
                                <strong>PLATEFORME {{ INSTANCE.get_departement_name }}</strong>
                            </h1>
                        </div>

                    </div>
                    <div class="col-md-6 hidden-sm hidden-xs">

                        <div class="cadre-blanc cadre-rf">
                            <img alt="Logo République Française"
                                 src="{% static 'portail/img/Logo_de_la_Republique_francaise_102x60.png' %}">
                            <span class="cadre-rf-text">Ministère des Sports</span>
                        </div>

                    </div>
                </div>
                <!-- eof ligne de titre -->

                <!-- bof ligne de boutons dynamiques -->
                <div class="row">

                {% if not HIDE_CALENDAR %}
                    {% if not user.is_authenticated %}
                        <div class="col-lg-4  button-home">
                    {% else %}
                        <div class="col-md-6  button-home">
                    {% endif %}
                            <a href="{% url 'portail:calendar' %}" class="btn btn-block" role="button">
                                <i class="far fa-calendar-alt"></i>
                                <h2 class="text-center h2-home">Calendrier</h2>
                                <span class="">Les manifestations sportives sur le département</span>
                            </a>
                        </div>
                {% endif %}

                {% if not user.is_authenticated %}
                    {% if not HIDE_CALENDAR %}
                        <div class="col-lg-4  button-home">
                    {% else %}
                        <div class="col-md-6  button-home">
                    {% endif %}
                            <a href="{% url 'inscription_organisateur' %}" class="btn btn-block" role="button">
                                <i class="fas fa-user-plus"></i>
                                <h2 class="text-center h2-home">Inscription</h2>
                                <span class="">Organisateurs d'évenements sportifs, inscrivez-vous !</span>
                            </a>
                        </div>
                {% endif %}

                    {% if not HIDE_CALENDAR and not user.is_authenticated %}
                        <div class="col-lg-4  button-home">
                    {% elif HIDE_CALENDAR and user.is_authenticated %}
                        <div class="col-md-12  button-home">
                    {% else %}
                        <div class="col-md-6  button-home">
                    {% endif %}
                            <a href="{% url "aide:help-page" path="sommaire" %}" class="btn btn-block" role="button">
                                <i class="far fa-life-ring"></i>
                                <h2 class="text-center h2-home">Aide & infos</h2>
                                <span class="text-center">Espace dédié aux organisateurs, fédérations et services instructeurs</span>
                            </a>
                        </div>

                </div>
                <!-- bof ligne de boutons dynamiques -->

            </div>
            <!-- bof 2e colonne -->

        </div>
        </div>
        <!-- bof contenu -->


    <script src="{% static 'portail/js/homepage.js' %}" type="text/javascript"></script>

    {% endblock %}
{% endblock %}