agreements/urls.py
# coding: utf-8
from django.urls import path, re_path

from .views import *


app_name = 'agreements'
urlpatterns = [
    path('dashboard/', Dashboard.as_view(), name='dashboard'),
    path('archives/', Archives.as_view(), name='archives'),

    # Service
    re_path('service/(?P<pk>\d+)/acknowledge/', ServiceAvisAcknowledge.as_view(), name='service_agreement_acknowledge'),
    re_path('service/(?P<pk>\d+)/resend/', ServiceAvisResend.as_view(), name='service_agreement_resend'),
    re_path('service/(?P<pk>\d+)/', ServiceAvisDetail.as_view(), name='service_agreement_detail'),

    # Fédération
    re_path('federation/(?P<pk>\d+)/acknowledge/', FederationAvisAcknowledge.as_view(), name='federal_agreement_acknowledge'),
    re_path('federation/(?P<pk>\d+)/resend/', FederationAvisResend.as_view(), name='federal_agreement_resend'),
    re_path('federation/(?P<pk>\d+)/', FederationAvisDetail.as_view(), name='federal_agreement_detail'),

    # Mairie
    re_path('townhall/(?P<pk>\d+)/acknowledge/', MairieAvisAcknowledge.as_view(), name='townhall_agreement_acknowledge'),
    re_path('townhall/(?P<pk>\d+)/resend/', MairieAvisResend.as_view(), name='townhall_agreement_resend'),
    re_path('townhall/(?P<pk>\d+)/', MairieAvisDetail.as_view(), name='townhall_agreement_detail'),

    # EDSR
    re_path('edsr/(?P<pk>\d+)/dispatch/', EDSRAvisDispatch.as_view(), name='edsr_agreement_dispatch'),
    re_path('edsr/(?P<pk>\d+)/format/', EDSRAvisFormat.as_view(), name='edsr_agreement_format'),
    re_path('edsr/(?P<pk>\d+)/acknowledge/', EDSRAvisAcknowledge.as_view(), name='edsr_agreement_acknowledge'),
    re_path('edsr/(?P<pk>\d+)/resend/', EDSRAvisResend.as_view(), name='edsr_agreement_resend'),
    re_path('edsr/(?P<pk>\d+)/', EDSRAvisDetail.as_view(), name='edsr_agreement_detail'),

    # GGD
    re_path('ggd/(?P<pk>\d+)/dispatch/', GGDAvisDispatch.as_view(), name='ggd_agreement_dispatch'),
    re_path('ggd/(?P<pk>\d+)/pass/', GGDAvisPass.as_view(), name='ggd_agreement_pass'),
    re_path('ggd/(?P<pk>\d+)/format/', GGDAvisFormat.as_view(), name='ggd_agreement_format'),
    re_path('ggd/(?P<pk>\d+)/acknowledge/', GGDAvisAcknowledge.as_view(), name='ggd_agreement_acknowledge'),
    re_path('ggd/(?P<pk>\d+)/resend/', GGDAvisResend.as_view(), name='ggd_agreement_resend'),
    re_path('ggd/(?P<pk>\d+)/', GGDAvisDetail.as_view(), name='ggd_agreement_detail'),

    # SDIS
    re_path('sdis/(?P<pk>\d+)/dispatch/', SDISAvisDispatch.as_view(), name='sdis_agreement_dispatch'),
    re_path('sdis/(?P<pk>\d+)/acknowledge/', SDISAvisAcknowledge.as_view(), name='sdis_agreement_acknowledge'),
    re_path('sdis/(?P<pk>\d+)/resend/', SDISAvisResend.as_view(), name='sdis_agreement_resend'),
    re_path('sdis/(?P<pk>\d+)/', SDISAvisDetail.as_view(), name='sdis_agreement_detail'),

    # DDSP
    re_path('ddsp/(?P<pk>\d+)/dispatch/', DDSPAvisDispatch.as_view(), name='ddsp_agreement_dispatch'),
    re_path('ddsp/(?P<pk>\d+)/acknowledge/', DDSPAvisAcknowledge.as_view(), name='ddsp_agreement_acknowledge'),
    re_path('ddsp/(?P<pk>\d+)/resend/', DDSPAvisResend.as_view(), name='ddsp_agreement_resend'),
    re_path('ddsp/(?P<pk>\d+)/', DDSPAvisDetail.as_view(), name='ddsp_agreement_detail'),

    # CG
    re_path('cg/(?P<pk>\d+)/dispatch/', CGAvisDispatch.as_view(), name='cg_agreement_dispatch'),
    re_path('cg/(?P<pk>\d+)/format/', CGAvisFormat.as_view(), name='cg_agreement_format'),
    re_path('cg/(?P<pk>\d+)/acknowledge/', CGAvisAcknowledge.as_view(), name='cg_agreement_acknowledge'),
    re_path('cg/(?P<pk>\d+)/resend/', CGAvisResend.as_view(), name='cg_agreement_resend'),
    re_path('cg/(?P<pk>\d+)/', CGAvisDetail.as_view(), name='cg_agreement_detail'),
]

api/urls.py
from django.urls import include, path
from api import views as api_views
from rest_framework import routers


app_name = 'api'
router = routers.DefaultRouter()
# router.register(r'manifestations', api_views.ManifestationAllViewSet)
router.register(r'ManifestationAutorisation', api_views.ManifestationAutorisationViewSet, base_name='ManifestationAutorisation')
router.register(r'ManifestationDeclaration', api_views.ManifestationDeclarationViewSet, base_name='ManifestationDeclaration')
router.register(r'Organisateur', api_views.OrganisateurViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

agreements/views/archives.py
# coding: utf-8
from django.utils.decorators import method_decorator
from django.views.generic import ListView

from core.util.permissions import require_role
from ..models import *


class Archives(ListView):
    """ Affichage de la liste d'avis des manifestations passées dans le dashboard """

    # Configuration
    model = Avis
    template_name_suffix = '_archives'

    @method_decorator(require_role('agent'))
    def dispatch(self, *args, **kwargs):
        return super(Archives, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        """ Selon le rôle de l'agent, renvoyer ce qu'il doit voir dans le dashboard """
        agent = self.request.user.agent
        instance = self.request.user.get_instance()
        user = self.request.user

        if user.has_role('federationagent'):
            return FederationAvis.objects.by_instance(request=self.request).finished().for_federation(agent.federationagent.federation)
        elif user.has_role('serviceagent'):
            return ServiceAvis.objects.finished().filter(service=agent.serviceagent.service)
        elif user.has_role('mairieagent'):
            return MairieAvis.objects.finished().filter(commune=agent.mairieagent.commune)
        elif user.has_role('edsragent'):
            if instance.get_workflow_ggd() == Instance.WF_EDSR:
                return EDSRAvis.objects.by_instance(request=self.request).finished()
            elif instance.get_workflow_ggd() == Instance.WF_GGD_EDSR:
                return GGDAvis.objects.by_instance(request=self.request).with_edsr().finished()
            else:
                return EDSRAvis.objects.none()
        elif user.has_role('sdisagent'):
            return SDISAvis.objects.by_instance(request=self.request).finished()
        elif user.has_role('ddspagent'):
            return DDSPAvis.objects.by_instance(request=self.request).finished()
        elif user.has_role('ggdagent'):
            if instance.get_workflow_ggd() == Instance.WF_EDSR:
                return EDSRAvis.objects.by_instance(request=self.request).finished().to_acknowledge()
            else:
                return GGDAvis.objects.by_instance(request=self.request).finished()
        elif user.has_role('cgagent'):
            return CGAvis.objects.by_instance(request=self.request).finished()
        elif user.has_role('cgsuperieuragent'):
            return CGAvis.objects.by_instance(request=self.request).finished().to_acknowledge()
        elif user.has_role('codisagent'):
            return SDISAvis.objects.by_instance(request=self.request).finished().acknowledged()
        elif user.has_role('cisagent'):
            return SDISAvis.objects.by_instance(request=self.request).finished().for_fire_service(agent.cisagent.cis).acknowledged()
        elif user.has_role('brigadeagent'):
            if instance.get_workflow_ggd() == Instance.WF_EDSR:
                return EDSRAvis.objects.by_instance(request=self.request).finished()
            elif instance.get_workflow_ggd() in [Instance.WF_GGD_EDSR, Instance.WF_GGD_SUBEDSR]:
                return GGDAvis.objects.by_instance(request=self.request).finished()
            else:
                return None

    def get_context_data(self, **kwargs):
        context = super(Archives, self).get_context_data(**kwargs)
        return context

agreements/views/base.py
# coding: utf-8
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.views.generic import View
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import UpdateView

from core.util.permissions import require_role
from ..forms import *
from ..models import *


class BaseAcknowledgeView(UpdateView):
    """ Vue de base pour rendre un avis """

    # Configuration
    model = Avis
    form_class = AvisAcknowledgeForm
    template_name_suffix = '_ack_form'

    # Overrides
    def form_valid(self, form):
        """ Le formulaire est valide, gérer la réponse HTTP """
        if form.instance.state == 'acknowledged':
            messages.error(self.request, "Aucune action effectuée : cet avis a déjà été validé.")
            return HttpResponseRedirect(self.get_success_url())
        else:
            form.instance.acknowledge()
            return super(BaseAcknowledgeView, self).form_valid(form)

    def get_initial(self):
        """ Renvoyer les valeurs de base du formulaire """
        initial = super().get_initial()
        initial['favorable'] = True
        return initial


class BaseFormatView(UpdateView):
    """ Vue de base pour mettre en forme un avis (étape avant la rendu) """

    # Configuration
    model = Avis
    form_class = AvisFormatForm
    template_name_suffix = '_format_form'

    # Overrides
    def form_valid(self, form):
        """ Le formulaire est valide, gérer la réponse HTTP """
        if form.instance.state == 'formatted':
            messages.error(self.request, "Aucune action effectuée : cet avis a déjà été mis en forme.")
            return HttpResponseRedirect(self.get_success_url())
        else:
            form.instance.format()
            return super(BaseFormatView, self).form_valid(form)


class BaseDispatchView(UpdateView):
    """ Vue de base pour envoyer les demandes de préavis """

    # Configuration
    template_name_suffix = '_dispatch_form'

    # Overrides
    def form_valid(self, form):
        """ Le formulaire est valide, gérer la réponse HTTP """
        if form.instance.state == 'dispatched':
            messages.error(self.request, "Aucune action effectuée : les demandes de pré-avis ont déjà été envoyées.")
            return HttpResponseRedirect(self.get_success_url())
        else:
            form.instance.dispatch()
            return super(BaseDispatchView, self).form_valid(form)


class BaseResendView(SingleObjectMixin, View):
    """ Vue de base pour renvoyer des demandes de préavis """

    # Configuration
    model = Avis

    # Overrides
    @method_decorator(require_role(['instructeur', 'mairieagent']))
    def dispatch(self, *args, **kwargs):
        """
        Gérer la méthode d'entrée de la vue (GET, POST)

        Ici, on ne fait que protéger toutes les méthodes d'entrée pour ne donner
        accès à la page qu'au rôle instructeur
        """
        return super(BaseResendView, self).dispatch(*args, **kwargs)

agreements/views/cg.py
# coding: utf-8
from django.contrib import messages
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.views.generic import DetailView

from administration.models.service import CGService
from agreements.views.base import BaseAcknowledgeView, BaseResendView, BaseDispatchView, BaseFormatView
from core.util.permissions import require_role
from ..forms import *
from ..models import *


class CGAvisDetail(DetailView):
    """ Vue de détail pour les avis CD """

    # Configuration
    model = CGAvis

    # Overrides
    @method_decorator(require_role(['cgagent', 'cgsuperieuragent']))
    def dispatch(self, *args, **kwargs):
        """ Autoriser la vue pour les agents CD uniquement """
        return super(CGAvisDetail, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Affichage des pictos de la manifestation
        type_name = self.object.authorization.manifestation.get_manifestation_type_name()
        dict = {'autorisationnm': 'anm', 'declarationnm': 'dnm', 'motorizedconcentration': 'avtmc', 'motorizedevent': 'avtm', 'motorizedrace': 'avtmcir'}
        context['type'] = dict[type_name]
        return context


class CGAvisDispatch(BaseDispatchView):
    """ Vue d'envoi des demandes de préavis """

    # Confioguration
    model = CGAvis
    form_class = CGAvisDispatchForm

    # Overrides
    @method_decorator(require_role(['cgagent', 'cgsuperieuragent']))
    def dispatch(self, *args, **kwargs):
        """ Autoriser la vue pour les agents CD uniquement """
        return super(CGAvisDispatch, self).dispatch(*args, **kwargs)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        # Filtrer les services dispo à ceux des départements traversés
        form.fields['concerned_services'].queryset = CGService.objects.filter(cg__departement__in=self.object.get_manifestation().get_crossed_departements())
        return form


class CGAvisFormat(BaseFormatView):
    """ Vue de mise en forme d'un avis CD """

    # Configuration
    model = CGAvis

    # Overrides
    @method_decorator(require_role(['cgagent', 'cgsuperieuragent']))
    def dispatch(self, *args, **kwargs):
        """ Autoriser la vue pour les agents CD uniquement """
        return super(CGAvisFormat, self).dispatch(*args, **kwargs)


class CGAvisAcknowledge(BaseAcknowledgeView):
    """ Vue de rendu de l'avis CD """

    # Configuration
    model = CGAvis

    # Overrides
    @method_decorator(require_role(['cgagent', 'cgsuperieuragent']))
    def dispatch(self, *args, **kwargs):
        """ Autoriser la vue pour les agents supérieurs CD uniquement """
        return super(CGAvisAcknowledge, self).dispatch(*args, **kwargs)


class CGAvisResend(BaseResendView):
    """ Vue de renvoi des demandes d'avis """

    # Configuration
    model = CGAvis

    # Overrides
    def get(self, request, *args, **kwargs):
        """ Vue pour la méthode GET """
        instance = self.get_object()
        instance.notify_creation(agents=instance.authorization.manifestation.departure_city.get_departement().cg.cgagents.all())
        instance.log_resend(recipient=instance.get_cg().__str__())
        messages.success(request, "Demande d'avis relancée avec succès")
        return redirect(reverse('authorizations:authorization_detail', kwargs={'pk': instance.authorization.id}))

agreements/views/dashboard.py
# coding: utf-8
from django.utils.decorators import method_decorator
from django.views.generic import ListView

from core.util.permissions import require_role
from ..models import *


class Dashboard(ListView):
    """ Affichage de la liste d'avis dans le dashboard """

    # Configuration
    model = Avis

    @method_decorator(require_role('agent'))
    def dispatch(self, *args, **kwargs):
        return super(Dashboard, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        """ Selon le rôle de l'agent, renvoyer ce qu'il doit voir dans le dashboard """
        agent = self.request.user.agent
        instance = self.request.user.get_instance()
        user = self.request.user

        if user.has_role('federationagent'):
            return FederationAvis.objects.by_instance(request=self.request).to_process().for_federation(agent.federationagent.federation)
        elif user.has_role('serviceagent'):
            return ServiceAvis.objects.to_process().filter(service=agent.serviceagent.service)
        elif user.has_role('mairieagent'):
            return MairieAvis.objects.to_process().filter(commune=agent.mairieagent.commune)
        elif user.has_role('edsragent'):
            if instance.get_workflow_ggd() == Instance.WF_EDSR:
                return EDSRAvis.objects.by_instance(request=self.request).to_process()
            elif instance.get_workflow_ggd() == Instance.WF_GGD_EDSR:
                return GGDAvis.objects.by_instance(request=self.request).with_edsr().to_process()
            else:
                return EDSRAvis.objects.none()
        elif user.has_role('sdisagent'):
            return SDISAvis.objects.by_instance(request=self.request).to_process()
        elif user.has_role('ddspagent'):
            return DDSPAvis.objects.by_instance(request=self.request).to_process()
        elif user.has_role('ggdagent'):
            if instance.get_workflow_ggd() == Instance.WF_EDSR:
                return EDSRAvis.objects.by_instance(request=self.request).to_process().to_acknowledge()
            else:
                return GGDAvis.objects.by_instance(request=self.request).to_process()
        elif user.has_role('cgagent'):
            return CGAvis.objects.by_instance(request=self.request).to_process()
        elif user.has_role('cgsuperieuragent'):
            return CGAvis.objects.by_instance(request=self.request).to_process().to_acknowledge()
        elif user.has_role('codisagent'):
            return SDISAvis.objects.by_instance(request=self.request).to_process().acknowledged()
        elif user.has_role('cisagent'):
            return SDISAvis.objects.by_instance(request=self.request).to_process().for_fire_service(agent.cisagent.cis).acknowledged()
        elif user.has_role('brigadeagent'):
            if instance.get_workflow_ggd() == Instance.WF_EDSR:
                return EDSRAvis.objects.by_instance(request=self.request).to_process()
            elif instance.get_workflow_ggd() in [Instance.WF_GGD_EDSR, Instance.WF_GGD_SUBEDSR]:
                return GGDAvis.objects.by_instance(request=self.request).to_process()
            else:
                return None

    def get_context_data(self, **kwargs):
        context = super(Dashboard, self).get_context_data(**kwargs)
        return context

agreements/templates/agreements/avis_format_form.html
{% extends "base_form.html" %}

{% load i18n %}

{% block head_title %}
    Mettre en forme l'avis
{% endblock %}

{% block page_title %}
    <h1><i class="fas fa-pencil-alt" title="metre en forme"></i> Mettre en forme l'avis : {{ object.authorization.manifestation|capfirst }}
    <i class="fas fa-thumbs-up left-margin" title="préavis"></i></h1>
{% endblock %}

agreements/templates/agreements/cgavis_archives.html
{% extends "agreements/archives_agent.html" %}

{% block agreement_item %}
    href="{% url 'agreements:cg_agreement_detail' avis.id %}"
{% endblock %}

agreements/templates/agreements/cgavis_detail.html
{% extends "agreements/avis_detail.html" %}

{% load i18n %}

{% block agreement_actions %}
    {% if object.state == 'created' and request.user.agent.cgagent %}
        <a href="{% url 'agreements:cg_agreement_dispatch' pk=object.id %}" class="btn" role="button">
            <i class="fas fa-paper-plane" title="envoyer"></i> Envoyer les demandes de pré-avis
            <i class="fas fa-thumbs-up left-margin" title="préavis"></i>
        </a>
    {% elif object.state == 'dispatched' and request.user.agent.cgagent %}
        {% if object.are_preavis_validated %}
            <a href="{% url 'agreements:cg_agreement_format' pk=object.id %}" class="btn" role="button">
                <i class="fas fa-pencil-alt" title="mettre en forme"></i> Mettre en forme l'avis
                <i class="fas fa-key left-margin" title="avis"></i>
            </a>
        {% endif %}
    {% elif object.state == 'formatted' and request.user.agent.cgsuperieuragent %}
        <a href="{% url 'agreements:cg_agreement_acknowledge' pk=object.id %}" class="btn" role="button">
            <i class="fas fa-key" title="avis"></i> Rendre l'avis
        </a>
    {% endif %}
{% endblock %}

agreements/templates/agreements/ddspavis_archives.html
{% extends "agreements/archives_agent.html" %}

{% block agreement_item %}
    href="{% url 'agreements:ddsp_agreement_detail' avis.id %}"
{% endblock %}

agreements/templates/agreements/edsravis_list.html
{% extends "agreements/dashboard_agent.html" %}

{% block agreement_item %}
    href="{% url 'agreements:edsr_agreement_detail' avis.id %}"
{% endblock %}

agreements/templates/agreements/ggdavis_archives.html
{% extends "agreements/archives_agent.html" %}

{% block agreement_item %}
    href="{% url 'agreements:ggd_agreement_detail' avis.id %}"
{% endblock %}

agreements/templates/agreements/ggdavis_list.html
{% extends "agreements/dashboard_agent.html" %}

{% block agreement_item %}
    href="{% url 'agreements:ggd_agreement_detail' avis.id %}"
{% endblock %}

agreements/templates/agreements/mairieavis_archives.html
{% extends "agreements/archives_agent.html" %}

{% block agreement_item %}
    href="{% url 'agreements:townhall_agreement_detail' avis.id %}"
{% endblock %}

agreements/templates/agreements/mairieavis_list.html
{% extends "agreements/dashboard_agent.html" %}

{% block agreement_item %}
    href="{% url 'agreements:townhall_agreement_detail' avis.id %}"
{% endblock %}

agreements/templates/agreements/sdisavis_ack_form.html
{% extends "agreements/avis_ack_form.html" %}

agreements/templates/agreements/sdisavis_detail.html
{% extends "agreements/avis_detail.html" %}

{% load i18n %}

{% block agreement_actions %}
    {% if object.state == 'created' %}
        <a href="{% url 'agreements:sdis_agreement_dispatch' pk=object.id %}" class="btn" role="button">
            <i class="fas fa-paper-plane" title="envoyer"></i> Envoyer les demandes de pré-avis
            <i class="fas fa-thumbs-up left-margin" title="préavis"></i>
        </a>
    {% elif object.state == 'dispatched' %}
        {% if object.are_preavis_validated %}
            <a href="{% url 'agreements:sdis_agreement_acknowledge' pk=object.id %}" class="btn" role="button">
                <i class="fas fa-key" title="avis"></i> Rendre l'avis
            </a>
        {% endif %}
    {% endif %}
{% endblock %}

agreements/templates/agreements/sdisavis_list.html
{% extends "agreements/dashboard_agent.html" %}

{% block agreement_item %}
    href="{% url 'agreements:sdis_agreement_detail' avis.id %}"
{% endblock %}

agreements/templates/agreements/serviceavis_ack_form.html
{% extends "base_form.html" %}

{% load i18n %}

{% block head_title %}Rendre l'avis{% endblock %}
{% block page_title %}
    <h1><i class="fas fa-key" title="avis"></i> Rendre l'avis</h1>
{% endblock %}

agreements/templates/agreements/serviceavis_archives.html
{% extends "agreements/archives_agent.html" %}

{% block agreement_item %}
    href="{% url 'agreements:service_agreement_detail' avis.id %}"
{% endblock %}