api/urls.py
from django.urls import include, path
from api import views as api_views
from rest_framework import routers


app_name = 'api'
router = routers.DefaultRouter()
# router.register(r'manifestations', api_views.ManifestationAllViewSet)
router.register(r'ManifestationAutorisation', api_views.ManifestationAutorisationViewSet, base_name='ManifestationAutorisation')
router.register(r'ManifestationDeclaration', api_views.ManifestationDeclarationViewSet, base_name='ManifestationDeclaration')
router.register(r'Organisateur', api_views.OrganisateurViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

events/urls.py
# coding: utf-8
from django.urls import path, re_path

from events.views.autorisationnm import AutorisationNMFilesUpdate
from events.views.declarationnm import DeclarationNMFilesUpdate
from events.views.motorizedconcentration import MotorizedConcentrationFilesUpdate
from events.views.motorizedmanifestation import MotorizedEventFilesUpdate
from events.views.motorizedrace import MotorizedRaceFilesUpdate
from .views import ManifestationStartChoose
from .views import Dashboard
from .views import UnsupportedManifestationCreate
from .views import ManifestationInstructeurUpdate
from .views import AutorisationNMCreate
from .views import AutorisationNMDetail
from .views import AutorisationNMUpdate
from .views import CreateRoute
from .views import DeclarationNMChoose
from .views import DeclarationNMCreate
from .views import DeclarationNMDetail
from .views import DeclarationNMUpdate
from .views import DocumentComplementaireProvideView
from .views import DocumentComplementaireRequestView
from .views import MailToOrganisateursView
from .views import MailToTownHallsView
from .views import ManifestationChoose
from .views import ManifestationPublicDetail
from .views import MotorizedConcentrationCreate
from .views import MotorizedConcentrationDetail
from .views import MotorizedConcentrationUpdate
from .views import MotorizedEventChoose
from .views import MotorizedEventCreate
from .views import MotorizedEventDetail
from .views import MotorizedEventUpdate
from .views import MotorizedRaceCreate
from .views import MotorizedRaceDetail
from .views import MotorizedRaceUpdate
from .views import NonMotorizedEventChoose
from .views import PublicRoadMotorizedEventChoose
from organisateurs.views import StructureCreate


app_name = 'events'
urlpatterns = [

    # Tableau de bord principal
    path('dashboard/', Dashboard.as_view(), name="dashboard"),

    path('mail_to_promoters/', MailToOrganisateursView.as_view(), name='mail_to_promoters'),
    path('mail_to_townhalls/', MailToTownHallsView.as_view(), name='mail_to_townhalls'),
    path('structure/add', StructureCreate.as_view(), name='structure_add'),

    path('events/choose_start/', ManifestationStartChoose.as_view(), name='manifestation_start_choose'),
    path('events/create_route/', CreateRoute.as_view(), name='create_route'),
    path('events/choose/', ManifestationChoose.as_view(), name='manifestation_choose'),
    path('motorizedevents/choose', MotorizedEventChoose.as_view(), name="motorizedevent_choose"),
    path('nonmotorizedevents/choose', NonMotorizedEventChoose.as_view(), name="nonmotorizedevent_choose"),
    path('DeclarationNM/choose', DeclarationNMChoose.as_view(), name="declarationnm_choose"),
    path('publicroadmotorizedevents/choose', PublicRoadMotorizedEventChoose.as_view(), name="publicroadmotorizedevent_choose"),

    # Manifestation sans type (non supporté)
    path('unsupported/add/', UnsupportedManifestationCreate.as_view(), name="unsupported_manifestation_add"),

    # Modifications instructeur
    re_path('event/(?P<pk>\d+)/instruction/', ManifestationInstructeurUpdate.as_view(), name="manifestation_instructeur"),
    re_path('event/(?P<manifestation_pk>\d+)/additional_data/add', DocumentComplementaireRequestView.as_view(), name="additional_data_add"),
    re_path('event/(?P<pk>\d+)/', ManifestationPublicDetail.as_view(), name="manifestation_detail"),

    # DeclarationNM urls
    path('DeclarationNM/add/', DeclarationNMCreate.as_view(), name="declarationnm_add"),
    re_path('DeclarationNM/(?P<pk>\d+)/edit/', DeclarationNMUpdate.as_view(), name="declarationnm_update"),
    re_path('DeclarationNM/(?P<pk>\d+)/edit_files/', DeclarationNMFilesUpdate.as_view(), name="declarationnm_files_update"),
    re_path('DeclarationNM/(?P<pk>\d+)/', DeclarationNMDetail.as_view(), name="declarationnm_detail"),

    # AutorisationNM urls
    path('AutorisationNM/add/', AutorisationNMCreate.as_view(), name="autorisationnm_add"),
    re_path('AutorisationNM/(?P<pk>\d+)/edit/', AutorisationNMUpdate.as_view(), name="autorisationnm_update"),
    re_path('AutorisationNM/(?P<pk>\d+)/edit_files/', AutorisationNMFilesUpdate.as_view(), name="autorisationnm_files_update"),
    re_path('AutorisationNM/(?P<pk>\d+)/', AutorisationNMDetail.as_view(), name="autorisationnm_detail"),

    # MotorizedConcentration urls
    path('motorizedconcentrations/add/', MotorizedConcentrationCreate.as_view(), name="motorizedconcentration_add"),
    re_path('motorizedconcentrations/(?P<pk>\d+)/edit/', MotorizedConcentrationUpdate.as_view(), name="motorizedconcentration_update"),
    re_path('motorizedconcentrations/(?P<pk>\d+)/edit_files/', MotorizedConcentrationFilesUpdate.as_view(), name="motorizedconcentration_files_update"),
    re_path('motorizedconcentrations/(?P<pk>\d+)/', MotorizedConcentrationDetail.as_view(), name="motorizedconcentration_detail"),

    # MotorizedEvent urls
    path('motorizedevents/add/', MotorizedEventCreate.as_view(), name="motorizedevent_add"),
    re_path('motorizedevents/(?P<pk>\d+)/edit/', MotorizedEventUpdate.as_view(), name="motorizedevent_update"),
    re_path('motorizedevents/(?P<pk>\d+)/edit_files/', MotorizedEventFilesUpdate.as_view(), name="motorizedevent_files_update"),
    re_path('motorizedevents/(?P<pk>\d+)/', MotorizedEventDetail.as_view(), name="motorizedevent_detail"),

    # MotorizedRace urls
    path('motorizedraces/add/', MotorizedRaceCreate.as_view(), name="motorizedrace_add"),
    re_path('motorizedraces/(?P<pk>\d+)/edit/', MotorizedRaceUpdate.as_view(), name="motorizedrace_update"),
    re_path('motorizedraces/(?P<pk>\d+)/edit_files/', MotorizedRaceFilesUpdate.as_view(), name="motorizedrace_files_update"),
    re_path('additional_data/(?P<pk>\d+)/', DocumentComplementaireProvideView.as_view(), name="additional_data_provide"),
    re_path('motorizedraces/(?P<pk>\d+)/', MotorizedRaceDetail.as_view(), name="motorizedrace_detail"),

]

events/forms/autorisationnm.py
# coding: utf-8
from ajax_select.fields import AutoCompleteField
from crispy_forms.layout import Layout, Fieldset, Field, HTML
from django.forms import ModelChoiceField
from django import forms

from core.forms.base import GenericForm
from events.forms.manifestation import FORM_WIDGETS, HELP_EXTRA_ACTIVITE
from events.models import AutorisationNM
from sports.models import Discipline
from .manifestation import ManifestationForm, FIELDS_MANIFESTATION, FIELDS_ROADS, FIELDS_FILES, FIELDS_MARKUP, FIELDS_MARKUP_CONV, FIELDS_NATURA2000


class AutorisationNMForm(ManifestationForm):
    """ Formulaire """
    FORM_WIDGETS['city_police_detail'] = forms.Textarea(attrs={'rows': 1, 'style': 'height: 34px'})
    FORM_WIDGETS['state_police_detail'] = forms.Textarea(attrs={'rows': 1, 'style': 'height: 34px'})
    FORM_WIDGETS['traffic_regulations_compliance_detail'] = forms.Textarea(attrs={'rows': 1, 'style': 'height: 34px', 'placeholder': 'nom de la voie et créneau horaire de passage'})
    FORM_WIDGETS['right_of_way_detail'] = forms.Textarea(attrs={'rows': 1, 'style': 'height: 34px', 'placeholder': 'nom de la voie et créneau horaire de passage'})
    FORM_WIDGETS['temporary_exclusive_roads_detail'] = forms.Textarea(attrs={'rows': 1, 'style': 'height: 34px', 'placeholder': 'nom de la voie et créneau horaire de passage'})
    FORM_WIDGETS['private_roads_detail'] = forms.Textarea(attrs={'rows': 1, 'style': 'height: 34px', 'placeholder': 'nom de la voie et créneau horaire de passage'})

    # Champs
    discipline = ModelChoiceField(label="Disciplines", required=False, queryset=Discipline.objects.filter(motorise=False))
    extra_activite = AutoCompleteField('activite_nm', label="Recherche d'activité sportive", required=False,
                                       help_text=HELP_EXTRA_ACTIVITE, show_help_text=False)

    # Overrides
    def __init__(self, *args, **kwargs):
        super(AutorisationNMForm, self).__init__(*args, **kwargs)
        self.helper.layout = Layout(HTML("<p>Remplissez ce formulaire puis vous pourrez joindre ensuite des fichiers à votre dossier.</p><hr>"),
                                    Fieldset(*(FIELDS_MANIFESTATION[:8] + ['affiliation'] + FIELDS_MANIFESTATION[8:] + ['multisport_federation'])),
                                    Fieldset("Coordonnateur Sécurité", 'safety_name', 'safety_firstname', 'safety_tel', 'safety_email'),
                                    Fieldset(*FIELDS_ROADS),
                                    Fieldset("Régime demandé en matière de circulation publique",
                                             Field('traffic_regulations_compliance', css_class='traffic'), 'traffic_regulations_compliance_detail',
                                             Field('right_of_way', css_class='traffic'), 'right_of_way_detail',
                                             Field('temporary_exclusive_roads', css_class='traffic'), 'temporary_exclusive_roads_detail',
                                             Field('private_roads', css_class='traffic'), 'private_roads_detail'),
                                    Fieldset("Informations sur le dispositif de sécurité de la manifestation",
                                             Fieldset("Véhicules d'accompagnement :", 'opening_vehicle', 'heading_vehicle', 'trailing_vehicle', 'staff_vehicle', css_class='special_fieldset'),
                                             Fieldset("Signaleurs :", 'signalers_number', 'signalers_number_still', 'signalers_number_auto', 'signalers_number_moto', css_class='special_fieldset'),
                                             Fieldset("Forces de l'ordre :", 'city_police', 'city_police_detail', 'state_police', 'state_police_detail', css_class='special_fieldset')
                                             ),
                                    Fieldset(*FIELDS_MARKUP_CONV), Fieldset(*FIELDS_MARKUP),
                                    Fieldset(*(FIELDS_NATURA2000[:-3])))

    # Meta
    class Meta:
        model = AutorisationNM
        exclude = ('instance', 'structure', 'approval_request', 'motor_on_closed_road', 'motor_on_natura2000', 'rounds_safety', 'instance')
        widgets = FORM_WIDGETS


class AutorisationNMFilesForm(GenericForm):
    """ Formulaire """

    # Overrides
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['signalers_list'].required = False
        self.helper.layout = Layout(Fieldset(*(FIELDS_FILES[:-1] + ['signalers_list', 'cycling_techdata'])))
        self.helper.form_tag = False

    # Meta
    class Meta:
        model = AutorisationNM
        fields = ['manifestation_rules', 'organisateur_commitment', 'insurance_certificate', 'safety_provisions', 'doctor_attendance', 'additional_docs',
                  'rounds_safety', 'signalers_list', 'cycling_techdata']

events/forms/documentcomplementaire.py
# coding: utf-8

from crispy_forms.layout import Submit
from django import forms

from core.forms.base import GenericForm
from events.models import DocumentComplementaire


class DocumentComplementaireRequestForm(GenericForm):
    """ Formulaire """

    # Overrides
    def __init__(self, *args, **kwargs):
        super(DocumentComplementaireRequestForm, self).__init__(*args, **kwargs)
        self.helper.add_input(Submit('submit', "Envoyer la Demande d'Information"))

    # Meta
    class Meta:
        model = DocumentComplementaire
        fields = ['desired_information']


class DocumentComplementaireProvideForm(GenericForm):
    """ Formulaire """

    # Overrides
    def __init__(self, *args, **kwargs):
        super(DocumentComplementaireProvideForm, self).__init__(*args, **kwargs)
        self.helper.add_input(Submit('submit', "Fournir le Document"))

    # Nettoyage des données validées
    def clean_attached_document(self):
        data = self.cleaned_data['attached_document']
        if data is None:
            raise forms.ValidationError("La sélection d'un document est obligatoire")
        return data

    # Meta
    class Meta:
        model = DocumentComplementaire
        fields = ['attached_document']

events/views/autorisationnm.py
# coding: utf-8
from events.views.manifestation import ManifestationDetail, ManifestationCreate, ManifestationUpdate, ManifestationFilesUpdate
from ..forms import *
from ..models import *


class AutorisationNMDetail(ManifestationDetail):
    """ Détail de manifestation """

    # Configuration
    model = AutorisationNM


class AutorisationNMCreate(ManifestationCreate):
    """ Création d'une manifestation """

    # Configuration
    model = AutorisationNM
    form_class = AutorisationNMForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type'] = 'anm'
        return context


class AutorisationNMUpdate(ManifestationUpdate):
    """ Modification d'une manifestation """

    # Configuration
    model = AutorisationNM
    form_class = AutorisationNMForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type'] = 'anm'
        return context


class AutorisationNMFilesUpdate(ManifestationFilesUpdate):
    """ Ajout de fichiers à une manif """

    # Configuration
    model = AutorisationNM
    form_class = AutorisationNMFilesForm

events/views/base.py
# coding: utf-8
from django.utils.decorators import method_decorator
from django.views.generic.base import TemplateView

from core.util.permissions import require_role


class ChoiceView(TemplateView):
    """ Vue AJAX ?? """

    # Overrides
    @method_decorator(require_role('organisateur'))
    def dispatch(self, *args, **kwargs):
        return super(ChoiceView, self).dispatch(*args, **kwargs)

events/views/choice.py
# coding: utf-8
from django.utils.decorators import method_decorator
from django.views.generic.base import TemplateView

from administrative_division.models.departement import Departement
from core.util.permissions import require_role
from events.views.base import ChoiceView


class ChoiceView(TemplateView):
    """ Mixin de vue pour les pages de choix lors de la création de manifestation """

    # Overrides
    @method_decorator(require_role('organisateur'))
    def dispatch(self, *args, **kwargs):
        return super(ChoiceView, self).dispatch(*args, **kwargs)


class ManifestationStartChoose(ChoiceView):
    """ Sélection du département de départ de manifestation """

    # Configuration
    template_name = 'events/selection/event_departement_choose.html'

    # Overrides
    def get_context_data(self, **kwargs):
        departements = Departement.objects.configured().order_by('name')
        return {'departements': departements}


class ManifestationChoose(ChoiceView):
    """ S&lection de manifestation """

    # Configuration
    template_name = 'events/selection/event_choose.html'


class NonMotorizedEventChoose(ChoiceView):
    """ Choix """

    # Confoguration
    template_name = 'events/selection/nonmotorizedevent_choose.html'


class MotorizedEventChoose(ChoiceView):
    """ Choix """

    # Configuration
    template_name = 'events/selection/motorizedevent_choose.html'


class PublicRoadMotorizedEventChoose(ChoiceView):
    """ Choix """

    # Configuration
    template_name = 'events/selection/publicroadmotorizedevent_choose.html'

events/views/dashboard.py
# coding: utf-8
from django.utils.decorators import method_decorator
from django.views.generic import ListView

from core.util.permissions import require_role
from events.models import *
from organisateurs.models.structure import Structure


class Dashboard(ListView):
    """ Tableau de bord organisateur """

    # Configuration
    model = Manifestation
    template_name = 'events/dashboard_organisateur.html'

    # Overrides
    @method_decorator(require_role('organisateur'))
    def dispatch(self, *args, **kwargs):
        """ Protéger la vue pour un accès par les organisateurs uniquement """
        return super(Dashboard, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        """ Renvoyer les manifestations à afficher dans le tableau de bord """
        try:
            user_structure = self.request.user.organisateur.structure
        except Structure.DoesNotExist:
            user_structure = None
        return Manifestation.objects.filter(structure=user_structure).order_by('-pk')

    def get_context_data(self, **kwargs):
        context = super(Dashboard, self).get_context_data(**kwargs)
        return context

events/templates/events/selection/declarednonmotorizedevent_choose.html
{% extends "base.html" %}


{% load i18n %}

{% block head_title %}Choix du Type de Manifestation Non Motorisée{% endblock %}
{% block page_title %}
    <h1>
        <span class="fa-stack">
          <i class="fas fa-car fa-stack-1x"></i>
          <i class="fas fa-ban fa-stack-2x text-danger"></i>
        </span>
        <span class="fa-stack">
          <i class="fas fa-trophy fa-stack-1x"></i>
          <i class="fas fa-ban fa-stack-2x text-danger"></i>
        </span>
        Nombre de participants ? </h1>
{% endblock %}

{% block content %}
    <div class="col-sm-12">
        <div class="list-group">
            <a href="{% url 'events:declarationnm_add' %}?dept={{ request.GET.dept }}" class="list-group-item list-group-item-action">
                <h3>
                <span class="fa-stack">
                  <i class="fas fa-circle fa-stack-2x text-info"></i>
                  <i class="fas fa-users fa-stack-1x fa-inverse"></i>
                </span>
                    Oui</h3>
                Cette manifestation prévoit la circulation en un point déterminé de la voie publique ou de ses dépendances de : <br/>
                -  Plus de 100 participants
            </a>
            <a href="{% url 'events:dashboard' %}" class="list-group-item list-group-item-action">
                <h3>
                <span class="fa-stack">
                  <i class="fas fa-users fa-stack-1x"></i>
                  <i class="fas fa-ban fa-stack-2x text-danger"></i>
                </span>
                    Non</h3>
                La déclaration en préfecture n'est pas nécessaire dans ce cas<br/>
                <i class="fas fa-reply" title="retour"></i> Revenir au tableau de bord <i class="fas fa-tachometer-alt left-margin" title="tableau de bord"></i>
            </a>
        </div>
    </div>
{% endblock %}

events/templates/events/selection/event_choose.html
{% extends "base.html" %}


{% load i18n %}

{% block head_title %}Selection du type de manifestation{% endblock %}
{% block page_title %}
    <h1>Sélectionnez le type de manifestation sportive que vous souhaitez organiser</h1>
{% endblock %}

{% block content %}
    <div class="col-sm-12">
        <div class="list-group">
            <a href="{% url 'events:motorizedevent_choose' %}?dept={{ request.GET.dept }}" class="list-group-item list-group-item-action">
                <h3>
                    <span class="fa-stack">
                      <i class="fas fa-circle fa-stack-2x text-info"></i>
                      <i class="fas fa-car fa-stack-1x fa-inverse"></i>
                    </span>
                    Manifestation sportive avec participation de véhicules terrestres à moteur *</h3>
            </a>
            <a href="{% url 'events:nonmotorizedevent_choose' %}?dept={{ request.GET.dept }}" class="list-group-item list-group-item-action">
                <h3>
                    <span class="fa-stack">
                      <i class="fas fa-car fa-stack-1x"></i>
                      <i class="fas fa-ban fa-stack-2x text-danger"></i>
                    </span>
                    Manifestation sportive sans participation de véhicules terrestres à moteur *</h3>
            </a>
        </div>
        <p>* La notion de véhicules terrestres à moteur concerne les participants à la manifestation</p>

    </div>
{% endblock %}

events/templates/events/selection/event_departement_choose.html
{% extends "base.html" %}


{% load i18n %}

{% block head_title %}Selection du département de la manifestation{% endblock %}
{% block page_title %}
    <h1><i class="fas fa-map-marker-alt"></i>Sélectionnez le département où débute votre manifestation</h1>
{% endblock %}

{% block content %}
    <div class="col-sm-12">
        <div class="list-group">
            {% for departement in departements %}
                <a href="{% url 'events:create_route' %}?dept={{ departement.name }}" class="list-group-item list-group-item-action">
                    <h3>{{ departement }}</h3>
                </a>
            {% endfor %}
            <a href="{% url 'events:unsupported_manifestation_add' %}" class="list-group-item list-group-item-action">
                <h3>Autre département</h3>
            </a>
        </div>
    </div>
{% endblock %}

events/templates/events/selection/motorizedevent_choose.html
{% extends "base.html" %}


{% load i18n %}

{% block head_title %}Sélection du Type de Manifestation Sportive{% endblock %}
{% block page_title %}
    <h1>
        <span class="fa-stack">
          <i class="fas fa-circle fa-stack-2x text-info"></i>
          <i class="fas fa-car fa-stack-1x fa-inverse"></i>
        </span>
        Sélectionnez le type de manifestation sportive</h1>
{% endblock %}

{% block content %}
    <div class="col-sm-12">
        <div class="list-group">
            <a href="{% url 'events:publicroadmotorizedevent_choose' %}?dept={{ request.GET.dept }}" class="list-group-item list-group-item-action">
                <h3>
                    <span class="fa-stack">
                      <i class="fas fa-circle fa-stack-2x text-info"></i>
                      <i class="fas fa-road fa-stack-1x fa-inverse"></i>
                    </span>
                    Manifestation sportive sur voie publique ou ouverte à la circulation publique</h3>
                <ul>
                    <li>Les voies publiques : Les voies classées dans le domaine public routier de l'Etat, des
                        départements et des communes (voies communales, départementales, nationales, autoroutes)
                    </li>
                    <li>Les chemins ruraux : les chemins inscrits au domaine privé de la commune affectés à l'usage public</li>
                    <li>les voies privées ouvertes à la circulation publique des véhicules à moteur : <!--TODO definition--></li>
                </ul>
            </a>
            <a href="{% url 'events:motorizedrace_add' %}?dept={{ request.GET.dept }}" class="list-group-item list-group-item-action">
                <h3>
                    <span class="fa-stack">
                      <i class="fas fa-road fa-stack-1x"></i>
                      <i class="fas fa-ban fa-stack-2x text-danger"></i>
                    </span>
                    Manifestation hors voie publique ou ouverte à la circulation publique</h3>
                (Article R331-18 du code du sport)
                <ul>
                    <li>Regroupement de VTM et d'un ou plusieurs pilotes ou pratiquants</li>
                    <li>Visant à présenter, de façon organisée pour les spectateurs</li>
                    <li>Un sport mécanique sous ses différentes formes</li>
                </ul>
            </a>
        </div>
    </div>
{% endblock %}

events/templates/events/selection/nonmotorizedevent_choose.html
{% extends "base.html" %}


{% load i18n %}

{% block head_title %}Choix du Type de Manifestation Non Motorisée{% endblock %}
{% block page_title %}
    <h1>
        <span class="fa-stack">
          <i class="fas fa-car fa-stack-1x"></i>
          <i class="fas fa-ban fa-stack-2x text-danger"></i>
        </span>
        Vous organisez une compétition ? </h1>
{% endblock %}

{% block content %}
    <div class="col-sm-12">
        <div class="list-group">
            <a href="{% url 'events:autorisationnm_add' %}?dept={{ request.GET.dept }}" class="list-group-item list-group-item-action">
                <h3>
                    <span class="fa-stack">
                      <i class="fas fa-circle fa-stack-2x text-info"></i>
                      <i class="fas fa-trophy fa-stack-1x fa-inverse"></i>
                    </span>
                    Oui</h3>
                Avec horaire fixe ou classement, vitesse ou moyenne imposée
            </a>
            <a href="{% url 'events:declarationnm_choose' %}?dept={{ request.GET.dept }}" class="list-group-item list-group-item-action">
            <h3>
                    <span class="fa-stack">
                      <i class="fas fa-trophy fa-stack-1x"></i>
                      <i class="fas fa-ban fa-stack-2x text-danger"></i>
                    </span>
                    Non</h3>
            </a>
        </div>
    </div>
{% endblock %}

events/templates/events/selection/publicroadmotorizedevent_choose.html
{% extends "base.html" %}


{% load i18n %}

{% block head_title %}Sélection du type de manifestation sportive{% endblock %}
{% block page_title %}
    <h1>
        <span class="fa-stack">
          <i class="fas fa-circle fa-stack-2x text-info"></i>
          <i class="fas fa-car fa-stack-1x fa-inverse"></i>
        </span>
        <span class="fa-stack">
          <i class="fas fa-circle fa-stack-2x text-info"></i>
          <i class="fas fa-road fa-stack-1x fa-inverse"></i>
        </span>
        Sélectionnez le type de manifestation sportive</h1>
{% endblock %}

{% block content %}
    <div class="col-sm-12">
        <div class="list-group">
            <a href="{% url 'events:motorizedconcentration_add' %}?dept={{ request.GET.dept }}" class="list-group-item list-group-item-action">
                <h3>
                    <span class="fa-stack">
                      <i class="fas fa-trophy fa-stack-1x"></i>
                      <i class="fas fa-ban fa-stack-2x text-danger"></i>
                    </span>
                    Concentration de véhicules terrestres à moteur</h3>
                (Article R331-18 du code du sport)
                <ul>
                    <li>Un rassemblement comportant la participation d'au moins 50 VTM (circulation groupée)</li>
                    <li>Se déroulant sur la voie publique dans le respect du code de la route (pas de temps imposé ou chronométrage)</li>
                    <li>Imposant aux participants un ou plusieurs points de rassemblement</li>
                    <li>Dépourvue de tout classement</li>
                </ul>
            </a>
            <a href="{% url 'events:motorizedevent_add' %}?dept={{ request.GET.dept }}" class="list-group-item list-group-item-action">
                <h3>
                    <span class="fa-stack">
                      <i class="fas fa-circle fa-stack-2x text-info"></i>
                      <i class="fas fa-trophy fa-stack-1x fa-inverse"></i>
                    </span>
                    Une manifestation avec véhicules terrestres à moteur</h3>
                (Article R331-18 du code du sport)
                <ul>
                    <li>Regroupement de VTM et d'un ou plusieurs pilotes ou pratiquants</li>
                    <li>Visant à présenter, de façon organisée pour les spectateurs</li>
                    <li>Un sport mécanique sous ses différentes formes</li>
                    <li>Les manifestations comportent généralement un classement, un temps imposé ou un chronométrage.</li>
                    <li>Toute compétition ou démonstration est assimilée à une manifestation</li>
                </ul>
            </a>
        </div>
    </div>
{% endblock %}